---
- name: install AD-Domain-Services
  win_feature:
    name: AD-Domain-Services
    include_sub_features: yes
    include_management_tools: yes

- name: Set up AD controller
  win_domain:
    dns_domain_name: "{{ ad_domain_name }}"
    safe_mode_password: "{{ ad_safe_mode_password }}"
  register: active_directory_controllers

- name: Reboot node
  win_reboot:
  when: active_directory_controllers.reboot_required

- name: List Domain Controllers in domain
  win_shell: "nltest /dclist:{{ ad_domain_name }}"
  register: domain_list
  until: domain_list.stderr == ""
  retries: 10

- debug:
    var: domain_list
